<?php
/**
 * SoulMD Hub - Critical Legal Disclaimer Modal
 * Included dynamically in chat.php
 */
?>
<div id="disclaimer-modal" class="hidden fixed inset-0 bg-black/90 flex items-center justify-center z-[400] p-4 backdrop-blur-md">
    <div class="bg-zinc-900 border border-emerald-500/30 rounded-3xl max-w-2xl w-full max-h-[85vh] flex flex-col overflow-hidden shadow-2xl transform scale-100 transition-transform duration-300">
        
        <div class="p-6 border-b border-white/10 bg-zinc-950/40 shrink-0">
            <h3 class="text-xl font-bold tracking-tight text-amber-400 flex items-center gap-2">
                <i class="fas fa-gavel"></i> CRITICAL LEGAL DISCLAIMER & TERMS OF USAGE
            </h3>
            <p class="text-xs text-zinc-500 mt-1">You must review and accept this binding legal agreement before proceeding.</p>
        </div>
        
        <div class="p-6 overflow-y-auto space-y-5 text-xs text-zinc-300 leading-relaxed custom-scrollbar flex-grow bg-black/20">
            <div>
                <p class="font-bold text-white text-sm mb-1">1. NATURE OF GENERATIVE AI SYSTEMS AND PHENOMENON OF HALLUCINATION</p>
                <p>
                    By entering this session, you acknowledge and agree that you are interacting with an automated, generative artificial intelligence system utilizing large language models. This system synthesizes text based on algorithmic patterns and statistical probabilities rather than real-time factual lookup or human intelligence. You are explicitly warned that the output generated by this system may be entirely inaccurate, unverified, fabricated, or misleading. This is a known technical limitation commonly referred to as "hallucination." Under no circumstances shall any response generated be deemed a statement of fact, truth, or reflection of reality.
                </p>
            </div>
            
            <div>
                <p class="font-bold text-white text-sm mb-1">2. ABSOLUTE EXCLUSION OF PROFESSIONAL ADVICE</p>
                <p>
                    The outputs provided by this AI system are for educational, informational, and entertainment purposes only. Regardless of the predefined "Soul" configuration, persona, role, or profession (including but not limited to configurations mimicking software engineers, corporate lawyers, medical consultants, financial analysts, or legal engineers), the system is strictly legally prohibited from providing real, professional, binding advice. The platform and its operators do not offer professional consultations. Relying on any instruction, code block, financial projection, or legal assessment provided during this chat session is performed at your sole, unmitigated personal risk. You are strongly urged to consult licensed professionals before acting upon any text output.
                </p>
            </div>

            <div>
                <p class="font-bold text-white text-sm mb-1">3. PUBLIC URL ACCESS AND CRITICAL PRIVACY EXPOSURE WARNING</p>
                <p>
                    This platform utilizes an open, unauthenticated token-mapping architecture designed to facilitate absolute accessibility and seamless community collaboration. The exact URL of this chat session contains a unique token identifier. <strong class="text-amber-400">ANY INDIVIDUAL WHO ACQUIRES, POSSESSES, OR DISCOVERS THIS FULL URL WILL HAVE COMPLETE, UNRESTRICTED READ ACCESS TO THE ENTIRETY OF THE CHAT HISTORY GENERATED WITHIN THIS SESSION.</strong> There is no secondary password layer or user ownership lock guarding this data once a URL is leaked or shared. Consequently, you are strictly prohibited from transmitting, inputs, or pasting any Personally Identifiable Information (PII), proprietary source code, corporate trade secrets, passwords, financial credentials, or sensitive data. The platform explicitly disclaims any data privacy or confidentiality breaches arising from the distribution or loss of this URL token.
                </p>
            </div>

            <div>
                <p class="font-bold text-white text-sm mb-1">4. TOTAL LIMITATION OF LIABILITY AND INDEMNIFICATION</p>
                <p>
                    To the maximum extent permitted under applicable jurisdiction, SoulMD Hub, its parent entities, subsidiaries, officers, developers, and operators shall not be held liable for any direct, indirect, incidental, consequential, special, punitive, or exemplary damages. This includes, without limitation, damages for loss of profits, commercial losses, data destruction, system crashes, legal complications, or financial failures resulting directly or indirectly from your usage of, or reliance on, this chat interface. You agree to defend, indemnify, and hold harmless the operators from any claims, liabilities, or losses arising out of your violation of these terms or input transmission.
                </p>
            </div>

            <div>
                <p class="font-bold text-white text-sm mb-1">5. MODERATION, CAPACITY LIMITS, AND CHARACTER BOUNDARIES</p>
                <p>
                    To ensure high platform efficiency and prevent system resource exploitation, text input is rigorously capped at a maximum of <b class="text-emerald-400"><?= number_format($maxInputChars) ?></b> characters per transmission. Conversational short-term memory is dynamically compressed using sliding-window thresholds to preserve context without exceeding AI token limits. The platform reserves the absolute right to terminate, purge, or restrict access to any session without prior notice if abnormal or destructive activity is detected.
                </p>
            </div>
        </div>

        <div class="p-6 border-t border-white/10 bg-zinc-900 flex justify-end gap-3 shrink-0">
            <button onclick="declineDisclaimer()" class="px-5 py-2.5 border border-white/10 rounded-xl text-sm font-medium text-zinc-300 hover:bg-white/5 transition">Decline & Exit</button>
            <button onclick="acceptDisclaimer()" class="px-6 py-2.5 bg-emerald-500 text-zinc-950 rounded-xl font-bold text-sm shadow-lg hover:bg-emerald-400 transition transform hover:scale-105 duration-200">I Understand & Agree</button>
        </div>
    </div>
</div>