<?php
require_once __DIR__ . '/../private/config.php';
require_once __DIR__ . '/../private/src/Database.php';
require_once __DIR__ . '/../private/includes/seo.php';

session_start();

// 雙重防護機制：生成專屬 CSRF Token 防止 API 被盜用
if (empty($_SESSION['chat_csrf_token'])) {
    $_SESSION['chat_csrf_token'] = bin2hex(random_bytes(32));
}
$csrfToken = $_SESSION['chat_csrf_token'];

$db = Database::getInstance();
$pdo = $db->getConnection();

$soulId = (int)($_GET['soul_id'] ?? 0);
$sessionToken = $_GET['session_token'] ?? '';

// 如果沒有指定 Soul，跳回首頁
if (!$soulId) {
    header('Location: /browse');
    exit;
}

// 獲取 Soul 資訊 (只限公開的 Soul)
$stmt = $pdo->prepare("SELECT title, role, content, file_type FROM souls WHERE id = ? AND is_public = 1");
$stmt->execute([$soulId]);
$soul = $stmt->fetch();

if (!$soul) {
    http_response_code(404);
    include __DIR__ . '/404.php';
    exit;
}

// 核心邏輯：如果是第一次進入 (沒有 Session Token)，自動生成並跳轉到專屬 URL
if (empty($sessionToken)) {
    $newToken = bin2hex(random_bytes(16)); // 生成 32 字符的隨機 Token
    header("Location: /chat/{$soulId}/{$newToken}", true, 302);
    exit;
}

$pageTitle = 'Chat Session - ' . htmlspecialchars($soul['title']);
$pageDesc = 'Live interaction with this specialized AI persona architecture.';
$hideNavLinks = true; // 隱藏頂部多餘的導航連結，保持對話視窗乾淨
require_once __DIR__ . '/../private/includes/header.php';
?>

<div id="disclaimer-modal" class="fixed inset-0 bg-black/95 z-[100] flex items-center justify-center p-4 backdrop-blur-xl">
    <div class="bg-zinc-900 border border-white/10 rounded-3xl max-w-2xl w-full max-h-[85vh] flex flex-col overflow-hidden shadow-2xl transform scale-100 transition-transform duration-300">
        
        <div class="p-6 border-b border-white/10 bg-zinc-950/40 shrink-0">
            <h3 class="text-xl font-bold tracking-tight text-amber-400 flex items-center gap-2">
                <i class="fas fa-gavel"></i> CRITICAL LEGAL DISCLAIMER & TERMS OF USAGE
            </h3>
            <p class="text-xs text-zinc-500 mt-1">You must review and accept this binding legal agreement before proceeding.</p>
        </div>
        
        <div class="p-6 overflow-y-auto space-y-4 text-xs text-zinc-300 leading-relaxed custom-scrollbar flex-grow bg-black/20">
            <p class="font-semibold text-white">1. NATURE OF GENERATIVE AI SYSTEMS AND PHENOMENON OF HALLUCINATION</p>
            <p>
                By entering this session, you acknowledge and agree that you are interacting with an automated, generative artificial intelligence system utilizing large language models. This system synthesizes text based on algorithmic patterns and statistical probabilities rather than real-time factual lookup or human intelligence. You are explicitly warned that the output generated by this system may be entirely inaccurate, unverified, fabricated, or misleading. This is a known technical limitation commonly referred to as "hallucination." Under no circumstances shall any response generated be deemed a statement of fact, truth, or reflection of reality.
            </p>
            
            <p class="font-semibold text-white">2. ABSOLUTE EXCLUSION OF PROFESSIONAL ADVICE</p>
            <p>
                The outputs provided by this AI system are for educational, informational, and entertainment purposes only. Regardless of the predefined "Soul" configuration, persona, role, or profession (including but not limited to configurations mimicking software engineers, corporate lawyers, medical consultants, financial analysts, or legal engineers), the system is strictly legally prohibited from providing real, professional, binding advice. The platform and its operators do not offer professional consultations. Relying on any instruction, code block, financial projection, or legal assessment provided during this chat session is performed at your sole, unmitigated personal risk. You are strongly urged to consult licensed professionals before acting upon any text output.
            </p>

            <p class="font-semibold text-white">3. PUBLIC URL ACCESS AND CRITICAL PRIVACY EXPOSURE WARNING</p>
            <p>
                This platform utilizes an open, unauthenticated token-mapping architecture designed to facilitate absolute accessibility and seamless community collaboration. The exact URL of this chat session contains a unique token identifier. <strong>ANY INDIVIDUAL WHO ACQUIRES, POSSESSES, OR DISCOVERS THIS FULL URL WILL HAVE COMPLETE, UNRESTRICTED READ ACCESS TO THE ENTIRETY OF THE CHAT HISTORY GENERATED WITHIN THIS SESSION.</strong> There is no secondary password layer or user ownership lock guarding this data once a URL is leaked or shared. Consequently, you are strictly prohibited from transmitting, inputs, or pasting any Personally Identifiable Information (PII), proprietary source code, corporate trade secrets, passwords, financial credentials, or sensitive data. The platform explicitly disclaims any data privacy or confidentiality breaches arising from the distribution or loss of this URL token.
            </p>

            <p class="font-semibold text-white">4. TOTAL LIMITATION OF LIABILITY AND INDEMNIFICATION</p>
            <p>
                To the maximum extent permitted under applicable jurisdiction, SoulMD Hub, its parent entities, subsidiaries, officers, developers, and operators shall not be held liable for any direct, indirect, incidental, consequential, special, punitive, or exemplary damages. This includes, without limitation, damages for loss of profits, commercial losses, data destruction, system crashes, legal complications, or financial failures resulting directly or indirectly from your usage of, or reliance on, this chat interface. You agree to defend, indemnify, and hold harmless the operators from any claims, liabilities, or losses arising out of your violation of these terms or input transmission.
            </p>

            <p class="font-semibold text-white">5. MODERATION, CAPACITY LIMITS, AND CHARACTER BOUNDARIES</p>
            <p>
                To ensure high platform efficiency and prevent system resource exploitation, text input is rigorously capped at a maximum of <?= MAX_INPUT_CHARS ?> characters per transmission. Conversational short-term memory is bounded to the 10 most recent message exchanges, after which older data decays out of context. The platform reserves the absolute right to terminate, purge, or restrict access to any session without prior notice if abnormal or destructive activity is detected.
            </p>
        </div>
        
        <div class="p-4 border-t border-white/10 bg-zinc-950/50 flex items-center justify-end gap-3 shrink-0">
            <a href="/soul/<?= $soulId ?>" class="px-5 py-2.5 border border-white/10 rounded-xl text-xs font-semibold text-zinc-400 hover:bg-white/5 hover:text-white transition">
                Decline & Exit
            </a>
            <button onclick="acceptDisclaimer()" class="px-6 py-2.5 bg-emerald-500 hover:bg-emerald-400 text-zinc-950 rounded-xl font-bold text-xs shadow-lg shadow-emerald-500/10 transition">
                I AGREE AND ENTER CHAT
            </button>
        </div>
    </div>
</div>

<div class="max-w-4xl w-full mx-auto px-4 sm:px-6 py-4 flex flex-col h-[calc(100vh-80px)]">
    
    <div class="bg-zinc-900/80 border border-white/10 rounded-t-3xl p-4 flex justify-between items-center backdrop-blur-md shrink-0">
        <div class="flex items-center gap-3">
            <a href="/soul/<?= $soulId ?>" class="w-10 h-10 rounded-full bg-zinc-800 flex items-center justify-center text-zinc-400 hover:text-emerald-400 hover:bg-zinc-700 transition">
                <i class="fas fa-arrow-left"></i>
            </a>
            <div>
                <h1 class="text-lg font-bold text-white leading-tight"><?= htmlspecialchars($soul['title']) ?></h1>
                <p class="text-xs text-zinc-500 flex items-center gap-1">
                    <i class="fas fa-circle text-emerald-500 text-[8px] animate-pulse"></i> Active Persona Session
                </p>
            </div>
        </div>
        <div>
            <button onclick="shareChat(this)" class="px-4 py-2 bg-white/5 hover:bg-white/10 border border-white/10 rounded-xl text-sm font-medium transition flex items-center gap-2">
                <i class="fas fa-share-alt"></i> Share Chat
            </button>
        </div>
    </div>

    <div class="bg-amber-500/10 border-x border-b border-amber-500/20 p-3 text-xs text-amber-200/80 flex items-start gap-2 shrink-0">
        <i class="fas fa-shield-alt mt-0.5 text-amber-500"></i>
        <p><strong>Privacy Warning:</strong> Anyone with this specific URL can view the entire chat history. Do not share any personal, private, or sensitive information. Text input is strictly limited to <?= MAX_INPUT_CHARS ?> characters per message.</p>
    </div>

    <div id="chat-box" class="flex-grow bg-zinc-950 border-x border-white/10 overflow-y-auto p-4 sm:p-6 space-y-6 custom-scrollbar scroll-smooth">
        <div class="flex justify-center items-center h-full" id="loading-history">
            <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-emerald-400"></div>
        </div>
    </div>

    <div class="bg-zinc-900 border border-white/10 rounded-b-3xl p-4 shrink-0 flex flex-col gap-3">
        <form id="chat-form" class="relative flex items-end gap-3">
            <div class="flex-grow relative">
                <textarea id="chat-input" rows="1" maxlength="<?= MAX_INPUT_CHARS ?>" placeholder="Type your message here (max <?= MAX_INPUT_CHARS ?> characters)..." class="w-full bg-zinc-950 border border-white/10 rounded-2xl px-5 py-3.5 pr-16 text-sm focus:outline-none focus:border-emerald-400 resize-none custom-scrollbar text-white placeholder-zinc-500 transition shadow-inner" style="min-height: 48px; max-height: 120px;" oninput="updateCharCount(this)"></textarea>
                <div id="char-count" class="absolute bottom-3 right-4 text-[10px] text-zinc-500 font-mono select-none">0/<?= MAX_INPUT_CHARS ?></div>
            </div>
            <button type="submit" id="send-btn" class="h-12 px-6 bg-emerald-500 text-zinc-950 rounded-2xl font-bold hover:bg-emerald-400 transition flex items-center justify-center shrink-0 shadow-lg disabled:opacity-50 disabled:cursor-not-allowed">
                <i class="fas fa-paper-plane"></i>
            </button>
        </form>
    </div>
</div>

<script>
    const soulId = <?= $soulId ?>;
    const sessionToken = "<?= htmlspecialchars($sessionToken) ?>";
    const serverCsrfToken = "<?= $csrfToken ?>"; 
    const chatBox = document.getElementById('chat-box');
    const chatInput = document.getElementById('chat-input');
    const charCount = document.getElementById('char-count');
    const sendBtn = document.getElementById('send-btn');
    const chatForm = document.getElementById('chat-form');
    const disclaimerModal = document.getElementById('disclaimer-modal');

    // 🚨 完美重構：由 config.php 動態傳入限制次數及輸入字元限制
    let userMessageCount = 0;
    const MAX_FREE_TURNS = <?= MAX_FREE_TURNS ?>;
    const MAX_INPUT_CHARS = <?= MAX_INPUT_CHARS ?>;

    // 免責聲明同意邏輯
    const storageKey = `soulmd_agreement_${soulId}_${sessionToken}`;

    if (localStorage.getItem(storageKey) === 'true') {
        disclaimerModal.classList.add('hidden');
    } else {
        disclaimerModal.classList.remove('hidden');
    }

    function acceptDisclaimer() {
        localStorage.setItem(storageKey, 'true');
        disclaimerModal.classList.add('hidden');
        if (userMessageCount < MAX_FREE_TURNS) {
            chatInput.focus();
        }
    }

    // 檢查並鎖定達到上限的輸入框
    function enforceTrialLimit() {
        if (userMessageCount >= MAX_FREE_TURNS) {
            chatInput.disabled = true;
            sendBtn.disabled = true;
            chatInput.value = '';
            chatInput.placeholder = "Trial limit reached. Please download the soul file to continue.";
            
            // 渲染上限橫幅警告
            if (!document.getElementById('trial-limit-banner')) {
                const banner = document.createElement('div');
                banner.id = 'trial-limit-banner';
                banner.className = 'w-full bg-red-500/10 border border-red-500/20 p-4 rounded-2xl text-xs text-red-400 flex flex-col sm:flex-row items-center justify-between gap-3 shrink-0 transition-all';
                banner.innerHTML = `
                    <div class="flex items-center gap-2 text-left">
                        <i class="fas fa-exclamation-triangle text-amber-500 text-sm shrink-0"></i>
                        <div>
                            <strong class="text-white block font-semibold mb-0.5">Trial Limit Reached</strong>
                            You have reached the maximum trial capacity of ${MAX_FREE_TURNS} interactions for this preview session.
                        </div>
                    </div>
                    <a href="/soul/anonymous/${soulId}/unassigned/download" class="px-4 py-2 bg-red-500 text-white font-bold rounded-xl hover:bg-red-400 transition shadow-md whitespace-nowrap text-center text-[11px]">
                        <i class="fas fa-download mr-1"></i> Download SOUL.md
                    </a>
                `;
                chatForm.parentNode.insertBefore(banner, chatForm);
            }
        }
    }

    // Setup Marked.js for AI responses
    marked.setOptions({
        breaks: true,
        gfm: true,
        highlight: function(code, lang) {
            if (lang && hljs.getLanguage(lang)) {
                try { return hljs.highlight(code, { language: lang }).value; } catch (e) {}
            }
            return hljs.highlightAuto(code).value;
        }
    });

    // Auto-resize textarea
    chatInput.addEventListener('input', function() {
        this.style.height = 'auto';
        this.style.height = (this.scrollHeight) + 'px';
        if (this.value.trim() === '') {
            this.style.height = '48px';
        }
    });

    // Handle Enter to send
    chatInput.addEventListener('keydown', function(e) {
        if (e.key === 'Enter' && !e.shiftKey && userMessageCount < MAX_FREE_TURNS) {
            e.preventDefault();
            chatForm.dispatchEvent(new Event('submit'));
        }
    });

    function updateCharCount(el) {
        const len = el.value.length;
        charCount.innerText = `${len}/${MAX_INPUT_CHARS}`; // 🚨 動態字數顯示
        if (len >= MAX_INPUT_CHARS) charCount.classList.add('text-red-400');
        else charCount.classList.remove('text-red-400');
    }

    function shareChat(btn) {
        const url = window.location.href;
        navigator.clipboard.writeText(url).then(() => {
            const originalHtml = btn.innerHTML;
            btn.innerHTML = '<i class="fas fa-check text-emerald-400"></i> Copied URL!';
            btn.classList.add('border-emerald-400/50', 'text-white');
            setTimeout(() => { 
                btn.innerHTML = originalHtml; 
                btn.classList.remove('border-emerald-400/50', 'text-white'); 
            }, 2000);
        });
    }

    function appendMessage(role, content) {
        const msgDiv = document.createElement('div');
        msgDiv.className = `flex w-full ${role === 'user' ? 'justify-end' : 'justify-start'}`;
        
        const bubble = document.createElement('div');
        bubble.className = `max-w-[85%] rounded-2xl p-4 text-sm leading-relaxed shadow-sm ${
            role === 'user' 
            ? 'bg-emerald-500 text-zinc-950 rounded-tr-sm' 
            : 'bg-zinc-800 border border-white/5 text-zinc-200 rounded-tl-sm prose prose-invert prose-sm prose-emerald'
        }`;

        if (role === 'user') {
            bubble.textContent = content;
        } else {
            if (content === '...') {
                bubble.innerHTML = '<div class="flex gap-1 items-center h-4"><span class="w-1.5 h-1.5 bg-zinc-500 rounded-full animate-bounce"></span><span class="w-1.5 h-1.5 bg-zinc-500 rounded-full animate-bounce" style="animation-delay: 0.2s"></span><span class="w-1.5 h-1.5 bg-zinc-500 rounded-full animate-bounce" style="animation-delay: 0.4s"></span></div>';
            } else {
                bubble.innerHTML = DOMPurify.sanitize(marked.parse(content));
            }
        }

        msgDiv.appendChild(bubble);
        chatBox.appendChild(msgDiv);
        chatBox.scrollTop = chatBox.scrollHeight;
        return bubble;
    }

    async function loadChatHistory() {
        try {
            const res = await fetch(`/api/chat?soul_id=${soulId}&session_token=${sessionToken}`);
            const data = await res.json();
            
            if (document.getElementById('loading-history')) {
                document.getElementById('loading-history').remove();
            }

            if (data.success && data.messages.length > 0) {
                data.messages.forEach(msg => {
                    appendMessage(msg.role, msg.content);
                    if (msg.role === 'user') {
                        userMessageCount++;
                    }
                });
                enforceTrialLimit();
            } else {
                appendMessage('assistant', "Hello! I am initialized and running exactly per your custom architecture files. What would you like to discuss?");
            }
        } catch (e) {
            document.getElementById('loading-history').innerHTML = '<span class="text-red-400">Failed to load conversation history.</span>';
        }
    }

    chatForm.addEventListener('submit', async (e) => {
        e.preventDefault();
        
        if (userMessageCount >= MAX_FREE_TURNS) {
            enforceTrialLimit();
            return;
        }

        const message = chatInput.value.trim();
        if (!message) return;
        
        // 🚨 前端動態驗證長度
        if (message.length > MAX_INPUT_CHARS) {
            alert(`Message exceeds ${MAX_INPUT_CHARS} characters limit.`);
            return;
        }

        chatInput.value = '';
        chatInput.style.height = '48px';
        updateCharCount(chatInput);
        chatInput.disabled = true;
        sendBtn.disabled = true;

        appendMessage('user', message);
        userMessageCount++;
        
        const aiBubble = appendMessage('assistant', '...');

        try {
            const res = await fetch('/api/chat', {
                method: 'POST',
                headers: { 
                    'Content-Type': 'application/json',
                    'X-CSRF-Token': serverCsrfToken 
                },
                body: JSON.stringify({
                    soul_id: soulId,
                    session_token: sessionToken,
                    content: message
                })
            });

            const contentType = res.headers.get("content-type");
            if (!contentType || !contentType.includes("application/json")) {
                throw new Error("CLOUDFLARE_HTML");
            }

            const data = await res.json();

            if (data.success) {
                aiBubble.innerHTML = DOMPurify.sanitize(marked.parse(data.reply));
            } else {
                aiBubble.innerHTML = `<span class="text-red-400"><i class="fas fa-exclamation-circle"></i> ${data.error || 'Failed to get response.'}</span>`;
            }
        } catch (err) {
            if (err.message === "CLOUDFLARE_HTML") {
                aiBubble.innerHTML = `<span class="text-amber-400"><i class="fas fa-clock"></i> The AI Provider took too long to respond. The network might be busy, please try again.</span>`;
            } else {
                aiBubble.innerHTML = `<span class="text-red-400"><i class="fas fa-wifi"></i> Network error. Connection failed.</span>`;
            }
        } finally {
            if (userMessageCount < MAX_FREE_TURNS) {
                chatInput.disabled = false;
                sendBtn.disabled = false;
                chatInput.focus();
            } else {
                enforceTrialLimit();
            }
            chatBox.scrollTop = chatBox.scrollHeight;
        }
    });

    window.onload = loadChatHistory;
</script>

<?php require_once __DIR__ . '/../private/includes/footer.php'; ?>