<?php
return [
    'en' => [
        'Production Workflows & Enterprise Automation' => 'Production Workflows & Enterprise Automation',
        'UseCases Main Desc: SoulMD Hub transitions prompts from primitive hobbyist play-sandboxes into rigid enterprise-grade production architectures. By utilizing an infrastructure optimized for high-concurrency token routing and unredacted multi-file isolation, development crews and data analytic teams deploy specialized prompt nodes natively inside existing cross-origin operational loops.' => 'UseCases Main Desc: SoulMD Hub transitions prompts from primitive hobbyist play-sandboxes into rigid enterprise-grade production architectures. By utilizing an infrastructure optimized for high-concurrency token routing and unredacted multi-file isolation, development crews and data analytic teams deploy specialized prompt nodes natively inside existing cross-origin operational loops.',
        'Usecase Engineering Title' => '🛠️ Advanced Modular Programming Tree',
        'Usecase Engineering Desc: Technical software teams build a cascading developer persona pool. By nesting discrete rules across multiple directories, compilers leverage the multi-file architecture to inject code standards programmatically. The system maps identity limits seamlessly, creating an automated code linter capable of checking memory drops, edge-case validation failure, and micro-concurrency issues via standard text blocks.' => 'Usecase Engineering Desc: Technical software teams build a cascading developer persona pool. By nesting discrete rules across multiple directories, compilers leverage the multi-file architecture to inject code standards programmatically. The system maps identity limits seamlessly, creating an automated code linter capable of checking memory drops, edge-case validation failure, and micro-concurrency issues via standard text blocks.',
        'Usecase Automation Title' => '📡 Headless Cross-Origin Automation Routing',
        'Usecase Automation Desc: Power members scale their business automation layer by rotating secure authorization keys inside the developer dashboard. By invoking our direct backend gateway pathways, applications bypass traditional browser session scopes entirely. Businesses route high-concurrency requests natively from corporate backend structures, mobile terminals, or distributed automated daemons directly into our unredacted prompt sandbox.' => 'Usecase Automation Desc: Power members scale their business automation layer by rotating secure authorization keys inside the developer dashboard. By invoking our direct backend gateway pathways, applications bypass traditional browser session scopes entirely. Businesses route high-concurrency requests natively from corporate backend structures, mobile terminals, or distributed automated daemons directly into our unredacted prompt sandbox.',
        'Usecase Composable Title' => '🌿 Composable Dependency Trees & Repository Forking',
        'Usecase Composable Desc: Prompt architects build advanced collaborative models using repository cloning forks. An engineer can inherit a public base architecture layer, overlaying custom child prompt modifications to create nested, composable dependency networks. This allows modular code architectures to be swapped, mixed, and referenced across different accounts seamlessly, establishing a reliable, open-source template ecosystem.' => 'Usecase Composable Desc: Prompt architects build advanced collaborative models using repository cloning forks. An engineer can inherit a public base architecture layer, overlaying custom child prompt modifications to create nested, composable dependency networks. This allows modular code architectures to be swapped, mixed, and referenced across different accounts seamlessly, establishing a reliable, open-source template ecosystem.',
    ],
    'zh' => [
        'Production Workflows & Enterprise Automation' => '商業級生產工作流與企業自動化運轉',
        'UseCases Main Desc: SoulMD Hub transitions prompts from primitive hobbyist play-sandboxes into rigid enterprise-grade production architectures. By utilizing an infrastructure optimized for high-concurrency token routing and unredacted multi-file isolation, development crews and data analytic teams deploy specialized prompt nodes natively inside existing cross-origin operational loops.' => '跨域場景導言：SoulMD Hub 將傳統玩票性質的 AI 提示詞沙盒，升級為具備嚴格工業級強度的生產力架構。透過針對高併發 Token 路由優化的基礎設施與毫不妥協的多檔案模組隔離，工程團隊與數據分析小組能夠將定制的 Prompt 節點原生地嵌入到現有的跨網域（Cross-Origin）自動化執行鏈路中。',
        'Usecase Engineering Title' => '🛠️ 模組化極速代碼審查與 AST 語法樹分析',
        'Usecase Engineering Desc: Technical software teams build a cascading developer persona pool. By nesting discrete rules across multiple directories, compilers leverage the multi-file architecture to inject code standards programmatically. The system maps identity limits seamlessly, creating an automated code linter capable of checking memory drops, edge-case validation failure, and micro-concurrency issues via standard text blocks.' => '軟體技術團隊能建立一套具備級聯效應的工程師角色池。透過在不同目錄下嵌套分立的規則，編譯組能最大化利用多檔案架構程式化地注入代碼規範，完美勾勒出一個全自動的 Linter 審查網格，透過標準文字區塊直接檢查內存洩漏、邊界條件失效與微併發衝突。',
        'Usecase Automation Title' => '📡 Headless 遠端自動化與多租戶跨境 API 閘道',
        'Usecase Automation Desc: Power members scale their business automation layer by rotating secure authorization keys inside the developer dashboard. By invoking our direct backend gateway pathways, applications bypass traditional browser session scopes entirely. Businesses route high-concurrency requests natively from corporate backend structures, mobile terminals, or distributed automated daemons directly into our unredacted prompt sandbox.' => '進階付費用戶可以透過在開發者控制台一鍵重置輪替 Secret 授權密鑰，大幅度擴充企業的自動化業務層。透過直接呼叫我們的後端網關通道，遠端應用程式能完全繞過傳統的瀏覽器 Session 會話邊界，允許企業從自身的後台伺服器、手機終端或分散式常駐守護進程（Daemon），將高併發請求原生投遞到我們受保護的黑盒 Prompt 沙盒中。',
        'Usecase Composable Title' => '🌿 複合成型依賴樹與代碼庫分叉克隆',
        'Usecase Composable Desc: Prompt architects build advanced collaborative models using repository cloning forks. An engineer can inherit a public base architecture layer, overlaying custom child prompt modifications to create nested, composable dependency networks. This allows modular code architectures to be swapped, mixed, and referenced across different accounts seamlessly, establishing a reliable, open-source template ecosystem.' => '提示詞架構師能利用代碼庫克隆（Fork）建立高階的開源協作模型。開發者可以完美繼承一個公開的基礎架構層，並在此之上疊加自訂的子提示詞修飾，形成嵌套的、具備相依關係的 Composable 依賴樹結構。這使得模組化代碼在不同帳號間可以被自由調度、混合與跨引用，打造了極具信任度的開源範本經濟圈。',
    ]
];