<?php
/**
 * SoulMD Hub - i18n Translation Dictionary
 * Target: disclaimer-modal.php (Legal Disclaimer Modal)
 */

return [
    'en' => [
        'Disclaimer Title' => 'CRITICAL LEGAL DISCLAIMER & TERMS OF USAGE',
        'Disclaimer Subtitle' => 'You must review and accept this binding legal agreement before proceeding.',
        
        'Disclaimer H1' => '1. NATURE OF GENERATIVE AI SYSTEMS AND PHENOMENON OF HALLUCINATION',
        'Disclaimer P1' => 'By entering this session, you acknowledge and agree that you are interacting with an automated, generative artificial intelligence system utilizing large language models. This system synthesizes text based on algorithmic patterns and statistical probabilities rather than real-time factual lookup or human intelligence. You are explicitly warned that the output generated by this system may be entirely inaccurate, unverified, fabricated, or misleading. This is a known technical limitation commonly referred to as "hallucination." Under no circumstances shall any response generated be deemed a statement of fact, truth, or reflection of reality.',
        
        'Disclaimer H2' => '2. ABSOLUTE EXCLUSION OF PROFESSIONAL ADVICE',
        'Disclaimer P2' => 'The outputs provided by this AI system are for educational, informational, and entertainment purposes only. Regardless of the predefined "Soul" configuration, persona, role, or profession (including but not limited to configurations mimicking software engineers, corporate lawyers, medical consultants, financial analysts, or legal engineers), the system is strictly legally prohibited from providing real, professional, binding advice. The platform and its operators do not offer professional consultations. Relying on any instruction, code block, financial projection, or legal assessment provided during this chat session is performed at your sole, unmitigated personal risk. You are strongly urged to consult licensed professionals before acting upon any text output.',
        
        'Disclaimer H3' => '3. PUBLIC URL ACCESS AND CRITICAL PRIVACY EXPOSURE WARNING',
        'Disclaimer P3' => 'This platform utilizes an open, unauthenticated token-mapping architecture designed to facilitate absolute accessibility and seamless community collaboration. The exact URL of this chat session contains a unique token identifier. <strong class="text-amber-400">ANY INDIVIDUAL WHO ACQUIRES, POSSESSES, OR DISCOVERS THIS FULL URL WILL HAVE COMPLETE, UNRESTRICTED READ ACCESS TO THE ENTIRETY OF THE CHAT HISTORY GENERATED WITHIN THIS SESSION.</strong> There is no secondary password layer or user ownership lock guarding this data once a URL is leaked or shared. Consequently, you are strictly prohibited from transmitting, inputs, or pasting any Personally Identifiable Information (PII), proprietary source code, corporate trade secrets, passwords, financial credentials, or sensitive data. The platform explicitly disclaims any data privacy or confidentiality breaches arising from the distribution or loss of this URL token.',
        
        'Disclaimer H4' => '4. TOTAL LIMITATION OF LIABILITY AND INDEMNIFICATION',
        'Disclaimer P4' => 'To the maximum extent permitted under applicable jurisdiction, SoulMD Hub, its parent entities, subsidiaries, officers, developers, and operators shall not be held liable for any direct, indirect, incidental, consequential, special, punitive, or exemplary damages. This includes, without limitation, damages for loss of profits, commercial losses, data destruction, system crashes, legal complications, or financial failures resulting directly or indirectly from your usage of, or reliance on, this chat interface. You agree to defend, indemnify, and hold harmless the operators from any claims, liabilities, or losses arising out of your violation of these terms or input transmission.',
        
        'Disclaimer H5' => '5. MODERATION, CAPACITY LIMITS, AND CHARACTER BOUNDARIES',
        'Disclaimer P5' => 'To ensure high platform efficiency and prevent system resource exploitation, text input is rigorously capped at a maximum of <b class="text-emerald-400">:chars</b> characters per transmission. Conversational short-term memory is dynamically compressed using sliding-window thresholds to preserve context without exceeding AI token limits. The platform reserves the absolute right to terminate, purge, or restrict access to any session without prior notice if abnormal or destructive activity is detected.',
        
        'Decline & Exit' => 'Decline & Exit',
        'I Understand & Agree' => 'I Understand & Agree',
    ],
    
    'zh' => [
        'Disclaimer Title' => '重大法律免責聲明與使用條款',
        'Disclaimer Subtitle' => '在繼續之前，您必須審閱並同意此具法律約束力之協議。',
        
        'Disclaimer H1' => '1. 生成式 AI 系統之本質與幻覺現象 (Hallucination)',
        'Disclaimer P1' => '進入此對話工作階段，即表示您認知並同意您正在與一個運用大型語言模型的自動化生成式人工智能系統互動。此系統基於演算法模式與統計機率合成文字，而非基於實時的事實檢索或人類智慧。我們在此明確警告，本系統生成的輸出可能完全不準確、未體驗證、憑空捏造或具誤導性。這是業界已知的技術限制，通常被稱為「幻覺 (Hallucination)」。在任何情況下，任何生成的對話回覆均不得被視為事實陳述、真理或反映現實。',
        
        'Disclaimer H2' => '2. 絕對排除專業建議',
        'Disclaimer P2' => '此 AI 系統提供的輸出僅供教育、資訊與娛樂用途。無論預設的「靈魂 (Soul)」設定、角色或職業為何（包括但不限於模仿軟體工程師、企業律師、醫療顧問、財務分析師或法律工程師的設定），本系統在法律上嚴格禁止提供真實、專業且具約束力的建議。本平台及其營運商不提供專業諮詢。依賴此對話工作階段中提供的任何指示、程式碼區塊、財務預測或法律評估，其風險完全由您個人承擔。強烈建議您在根據任何文字輸出採取行動前，諮詢持牌之專業人士。',
        
        'Disclaimer H3' => '3. 公開網址存取權與重大隱私外洩警告',
        'Disclaimer P3' => '本平台採用開放的無驗證 Token 映射架構，旨在促進絕對的便利性與無縫的社群協作。此對話工作階段的確切網址包含一組獨特的 Token 識別碼。<strong class="text-amber-400">任何取得、擁有或發現此完整網址的個人，將擁有完全、不受限制的讀取權限，可瀏覽此工作階段內產生的所有對話歷史紀錄。</strong> 一旦網址外洩或被分享，將沒有第二層密碼或使用者擁有權鎖可保護這些資料。因此，嚴禁您在此傳輸、輸入或貼上任何個人識別資訊 (PII)、專有原始碼、企業商業機密、密碼、財務憑證或敏感資料。對於因散佈或遺失此網址 Token 所引起的任何資料隱私或機密性外洩，本平台明確聲明免責。',
        
        'Disclaimer H4' => '4. 責任之完全限制與損害賠償',
        'Disclaimer P4' => '在適用司法管轄區允許的最大範圍內，SoulMD Hub、其母實體、子公司、管理人員、開發人員與營運商，對任何直接、間接、附帶、衍生、特殊、懲罰性或懲戒性損害概不負責。這包括但不限於利潤損失、商業損失、資料銷毀、系統崩潰、法律糾紛，或因您使用或依賴此對話介面而直接或間接導致的財務失敗。您同意針對因您違反本條款或輸入傳輸而引起的任何索賠、責任或損失，為營運商辯護、進行賠償並使其免受損害。',
        
        'Disclaimer H5' => '5. 內容審核、容量限制與字元邊界',
        'Disclaimer P5' => '為確保平台的高效運作並防止系統資源遭濫用，文字輸入被嚴格限制為每次傳輸最多 <b class="text-emerald-400">:chars</b> 個字元。對話的短期記憶會透過滑動視窗閾值進行動態壓縮，以在不超出 AI Token 限制的情況下保留上下文。如果檢測到異常或破壞性活動，平台保留在不事先通知的情況下，絕對終止、清除或限制存取任何對話工作階段的權利。',
        
        'Decline & Exit' => '拒絕並離開',
        'I Understand & Agree' => '我明白並同意',
    ]
];